/**
 * Test suite for assertion SQL generation
 *
 * Validates the SQL generated by ga4EventsEnhanced assertions
 * against BigQuery to ensure syntax correctness and schema compatibility.
 */

// Load environment variables from tests/.env
require('dotenv').config({ path: require('path').join(__dirname, '.env') });

const { validateMultipleSQL } = require('./sqlValidator');
const ga4EventsEnhanced = require('../tables/ga4EventsEnhanced');

/**
 * Get configuration from environment variables with fallback defaults
 */
const getTestConfig = () => {
    const sourceTable = process.env.TEST_SOURCE_TABLE;

    if (!sourceTable) {
        throw new Error("A source table must be specified in the TEST_SOURCE_TABLE environment variable.");
    }

    return {
        sourceTable,
        incremental: false,
        test: true,
    };
};

const testConfig = getTestConfig();

// The raw export table lacks columns that exist in the enhanced table
// (data_is_final, event_date as DATE not STRING, session_id). Wrap it in a subquery
// that transforms the schema so BigQuery dry-run can validate the full SQL.
const testTableRef = `(select * replace(cast(event_date as date format 'YYYYMMDD') as event_date), true as data_is_final, concat(user_pseudo_id, cast((select value.int_value from unnest(event_params) where key = 'ga_session_id') as string)) as session_id from ${testConfig.sourceTable} where _table_suffix >= cast(current_date()-5 as string format 'YYYYMMDD'))`;

/**
 * Test: Validate dailyQuality assertion SQL generation with various configurations
 */
const testDailyQualityConfigurations = async () => {
    const configurations = [
        {
            name: 'Default config (daily + intraday, DAY_THRESHOLD)',
            config: testConfig,
        },
        {
            name: 'Daily only',
            config: {
                ...testConfig,
                includedExportTypes: { daily: true, fresh: false, intraday: false },
            },
        },
        {
            name: 'Daily + fresh + intraday',
            config: {
                ...testConfig,
                includedExportTypes: { daily: true, fresh: true, intraday: true },
            },
        },
        {
            name: 'Fresh only',
            config: {
                ...testConfig,
                includedExportTypes: { daily: false, fresh: true, intraday: false },
                dataIsFinal: { detectionMethod: 'DAY_THRESHOLD', dayThreshold: 1 },
            },
        },
        {
            name: 'EXPORT_TYPE detection method',
            config: {
                ...testConfig,
                dataIsFinal: { detectionMethod: 'EXPORT_TYPE' },
            },
        },
        {
            name: 'DAY_THRESHOLD with custom threshold',
            config: {
                ...testConfig,
                dataIsFinal: { detectionMethod: 'DAY_THRESHOLD', dayThreshold: 7 },
            },
        },
        {
            name: 'With excluded ecommerce event (purchase)',
            config: {
                ...testConfig,
                excludedEvents: ['session_start', 'first_visit', 'purchase'],
            },
        },
        {
            name: 'With custom timezone',
            config: {
                ...testConfig,
                timezone: 'Europe/Helsinki',
            },
        },
    ];

    const queries = configurations.map(({ name, config }) => ({
        name,
        sql: ga4EventsEnhanced.assertions.dailyQuality(testTableRef, config),
    }));

    const results = await validateMultipleSQL(queries, {
        location: process.env.BIGQUERY_LOCATION || 'US',
    });

    return results;
};

/**
 * Run all tests
 */
const runAllTests = async () => {
    console.log('\n');
    console.log('╔═══════════════════════════════════════════════════════════════════════════════╗');
    console.log('║                   GA4 EXPORT FIXER - ASSERTION SQL VALIDATION                  ║');
    console.log('╚═══════════════════════════════════════════════════════════════════════════════╝');
    console.log(`\nEnvironment: ${process.env.GOOGLE_CLOUD_PROJECT || 'default'}`);
    console.log(`Location: ${process.env.BIGQUERY_LOCATION || 'US'}`);
    console.log(`Source: ${testConfig.sourceTable}`);
    console.log(`Table ref: ${testTableRef}\n`);

    const results = [];

    try {
        console.log('\n\n📝 TEST: Daily Quality Assertion SQL Generation\n');
        const dailyQualityResults = await testDailyQualityConfigurations();
        dailyQualityResults.forEach(r => {
            results.push({ test: `dailyQuality: ${r.name}`, result: r });
        });

        // Summary
        console.log('\n\n');
        console.log('╔═══════════════════════════════════════════════════════════════════════════════╗');
        console.log('║                              TEST SUMMARY                                      ║');
        console.log('╚═══════════════════════════════════════════════════════════════════════════════╝\n');

        const passed = results.filter(r => r.result.success).length;
        const failed = results.filter(r => !r.result.success).length;
        const total = results.length;

        console.log(`Total Tests: ${total}`);
        console.log(`✅ Passed: ${passed}`);
        console.log(`❌ Failed: ${failed}\n`);

        if (failed > 0) {
            console.log('Failed Tests:');
            results.filter(r => !r.result.success).forEach(({ test, result }) => {
                console.log(`  ❌ ${test}`);
                console.log(`     Error: ${result.errorMessage}\n`);
            });
        }

        if (failed > 0) {
            console.error('⚠️  Some tests failed. Please review the errors above.\n');
            process.exit(1);
        } else {
            console.log('🎉 All tests passed!\n');
            process.exit(0);
        }

    } catch (error) {
        console.error('\n❌ Test suite failed with unexpected error:');
        console.error(error);
        process.exit(1);
    }
};

// Run tests if this file is executed directly
if (require.main === module) {
    runAllTests();
}

module.exports = {
    testDailyQualityConfigurations,
    runAllTests,
};
