/**
 * Test suite for GA4 Events Enhanced SQL generation
 * 
 * This test validates the SQL generated by ga4EventsEnhanced.js
 * against BigQuery to ensure syntax correctness and schema compatibility.
 */

// Load environment variables from tests/.env
require('dotenv').config({ path: require('path').join(__dirname, '.env') });

const { validateSQL, validateMultipleSQL } = require('./sqlValidator');
const ga4EventsEnhanced = require('../tables/ga4EventsEnhanced');

/**
 * Get configuration from environment variables with fallback defaults
 */
const getTestConfig = () => {
  const sourceTable = process.env.TEST_SOURCE_TABLE;
  
  if (!process.env.TEST_SOURCE_TABLE) {
  throw new Error("A source table must be specified in the TEST_SOURCE_TABLE environment variable.");

  }
  
  return {
    sourceTable,
    incremental: false,
    test: true
  };
};

/**
 * Test configuration for GA4 Events Enhanced
 */
const testConfig = getTestConfig();

/**
 * Test: Validate main query generation
 */
const testMainQuery = async () => {
  console.log('Testing: GA4 Events Enhanced - Main Query');
  console.log(`Source: ${testConfig.sourceTable}`);
  
  const sql = ga4EventsEnhanced.generateSql(testConfig);
  
  const result = await validateSQL(sql, {
    location: process.env.BIGQUERY_LOCATION || 'US',
    verbose: true,
  });
  
  return result;
};

/**
 * Test: Validate with different configurations
 */
const testDifferentConfigurations = async () => {
  const configurations = [
    {
      name: 'Daily only (no intraday)',
      config: {
        ...testConfig,
        includedExportTypes: { daily: true, intraday: false },
      },
    },
    {
      name: 'With custom timestamp',
      config: {
        ...testConfig,
        customTimestamParam: 'custom_event_timestamp',
      },
    },
    {
      name: 'Europe/Helsinki time zone',
      config: {
        ...testConfig,
        timezone: 'Europe/Helsinki',
      },
    },
    {
      name: 'With 0 bufferDays',
      config: {
        ...testConfig,
        bufferDays: 0,
      },
    },
    {
      name: 'DAY_THRESHOLD detection method',
      config: {
        ...testConfig,
        dataIsFinal: {
          detectionMethod: 'DAY_THRESHOLD',
          dayThreshold: 5,
        },
      },
    },
    {
      name: 'With sessionParams',
      config: {
        ...testConfig,
        sessionParams: ['param1', 'param2'],
      },
    },
    {
      name: 'With event_params promoted to columns',
      config: {
        ...testConfig,
        eventParamsToColumns: [
          { name: 'page_title', type: 'string' },
          { name: 'page_content_group', type: 'string', columnName: 'content_group'},
          { name: 'page_title_custom'},
        ],
      },
    },
    {
      name: 'With some event_params excluded',
      config: {
        ...testConfig,
        excludedEventParams: ['param2', 'param3'], // Example: exclude these event parameters
      },
    },
    {
      name: 'With some events excluded',
      config: {
        ...testConfig,
        excludedEvents: ['event1', 'event2'], // Example: exclude these events
      },
    },
  ];
  
  const queries = configurations.map(({ name, config }) => ({
    name,
    sql: ga4EventsEnhanced.generateSql(config),
  }));
  
  const results = await validateMultipleSQL(queries, {
    location: process.env.BIGQUERY_LOCATION || 'US',
  });
  
  return results;
};

/**
 * Run all tests
 */
const runAllTests = async () => {
  console.log('\n');
  console.log('╔═══════════════════════════════════════════════════════════════════════════════╗');
  console.log('║                     GA4 EXPORT FIXER - SQL VALIDATION TESTS                   ║');
  console.log('╚═══════════════════════════════════════════════════════════════════════════════╝');
  console.log(`\nEnvironment: ${process.env.GOOGLE_CLOUD_PROJECT || 'default'}`);
  console.log(`Location: ${process.env.BIGQUERY_LOCATION || 'US'}`);
  console.log(`Source: ${testConfig.sourceTable}\n`);
  
  const results = [];
  
  try {
    // Test 1: Main query
    console.log('\n\n📝 TEST 1: Main Query Validation\n');
    const mainResult = await testMainQuery();
    results.push({ test: 'Main Query', result: mainResult });
    
    // Test 2: Different configurations
    console.log('\n\n📝 TEST 2: Different Configurations\n');
    const configResults = await testDifferentConfigurations();
    configResults.forEach(r => {
      results.push({ test: `Config: ${r.name}`, result: r });
    });

    // Summary
    console.log('\n\n');
    console.log('╔═══════════════════════════════════════════════════════════════════════════════╗');
    console.log('║                              TEST SUMMARY                                      ║');
    console.log('╚═══════════════════════════════════════════════════════════════════════════════╝\n');
    
    const passed = results.filter(r => r.result.success).length;
    const failed = results.filter(r => !r.result.success).length;
    const total = results.length;
    
    console.log(`Total Tests: ${total}`);
    console.log(`✅ Passed: ${passed}`);
    console.log(`❌ Failed: ${failed}\n`);
    
    if (failed > 0) {
      console.log('Failed Tests:');
      results.filter(r => !r.result.success).forEach(({ test, result }) => {
        console.log(`  ❌ ${test}`);
        console.log(`     Error: ${result.errorMessage}\n`);
      });
    }
    
    // Exit with error code if any tests failed
    if (failed > 0) {
      console.error('⚠️  Some tests failed. Please review the errors above.\n');
      process.exit(1);
    } else {
      console.log('🎉 All tests passed!\n');
      process.exit(0);
    }
    
  } catch (error) {
    console.error('\n❌ Test suite failed with unexpected error:');
    console.error(error);
    process.exit(1);
  }
};

// Run tests if this file is executed directly
if (require.main === module) {
  runAllTests();
}

module.exports = {
  testMainQuery,
  testDifferentConfigurations,
  runAllTests,
};
